In [2]:
import numpy as np

In [3]:
a = np.array([4, 10, 12, 23, -2, -1,0, 0, -6, 3, -7])

In [13]:
#how many negative numbers are there?

a < 0
sum(a<0)
#len(a(a<0))

4

In [14]:
#how many positive numbers are there?
a > 0
sum(a>0)
#len(a(a>0))

5

In [39]:
#how many even positive numbers are there?  use the and symbol and not the "and " word
positive_even = (a > 0) & (a % 2 == 0)
sum (positive_even)
#len(a[a>0 and a % 2 = 0])

3

In [44]:
#if you were to add 3 to each data point, 
#how many positive numbers would there be?
(a + 3)>0
sum((a + 3)>0)

9

In [49]:
a+3 

array([ 7, 13, 15, 26,  1,  2,  3,  3, -3,  6, -4])

In [59]:
#if you squared each number, 
#what would the new mean and standard deviation be?
a**2
#(a ** 2).mean()

array([ 16, 100, 144, 529,   4,   1,   0,   0,  36,   9,  49])

In [70]:
new_mean = a**2
new_mean.mean()

80.72727272727273

In [72]:
new_mean.std()     #good example of a method call

148.61242509481494

In [75]:
#A common statistical operation on a dataset is centering.
#This means to adjust the data such that the mean of the data is 0.
#this is done by subtracting the mean from each data point. 
#center the data set. 
#calculate the z score for each data point. recall that the z-score 
#is given by formula:
# z_scores = (data - np.mean(data)) / np.std(data)
z_scores = (a -np.mean(a))/np.std(a)
z_scores


array([ 0.08691546,  0.80396797,  1.04298547,  2.35758175, -0.63013706,
       -0.5106283 , -0.39111955, -0.39111955, -1.10817207, -0.0325933 ,
       -1.22768082])

In [ ]:
#Copy the setup and exercise directions from More Numpy Practice into your
#numpy_exercises.py and add your solutions.


In [77]:
import numpy as np
# Life w/o numpy to life with numpy

In [81]:

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Use python's built in functionality/operators to determine the following:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list
sum_of_a = sum(a)

55

In [82]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list
min_of_a = min(a)

1

In [83]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list
max_of_a = max(a)

10

In [91]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list


mean_of_a = ((sum(a))/10)
mean_of_a

5.5

In [92]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together

product_of_a = np.prod(a)
product_of_a

3628800

In [97]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]
squares_of_a = np.square(a)
squares_of_a

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [134]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = []
for odd in a:
    if (odd % 2 != 0):
        odds_in_a.append(odd)
odds_in_a        

[1, 3, 5, 7, 9]

In [138]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = []
for even in a: 
    if (even % 2 == 0):
        evens_in_a.append(even)
evens_in_a

[2, 4, 6, 8, 10]

In [ ]:
## What about life in two dimensions? A list of lists is matrix, a table, a spreadsheet, a chessboard...
## Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = [
    [3, 4, 5],
    [6, 7, 8]
]

In [142]:

# Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. 
#**Hint, you'll first need to make sure that the "b" variable is a numpy array**
sum_of_b = 0
for row in b:
    sum_of_b += sum(row)

sum_of_b += sum(row)
print(sum_of_b)

54


In [141]:

# Exercise 2 - refactor the following to use numpy. 
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

In [ ]:

# Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

max_of_b = np.max(b)
print(max_of_bd)

In [143]:

# Exercise 4 - refactor the following using numpy to find the mean of b
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

mean_of_b= np.mean(b)
print(mean_of_b)



5.5


In [ ]:
# Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
product_of_b = np.product(b)
print(product_of_b)

In [144]:
# Exercise 6 - refactor the following to use numpy to find the list of squares 
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
    
squares_of_b = np.square(b)
print(np.reshape(squares_of_b, 6))

[ 9 16 25 36 49 64]


In [ ]:
# Exercise 7 - refactor using numpy to determine the odds_in_b
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
            
            


In [ ]:

# Exercise 8 - refactor the following to use numpy to filter only the even numbers
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
            
evens_in_b = b[b %2 == 0]
print(evens_in_b)

In [ ]:
# Exercise 9 - print out the shape of the array b.
print(np.shape(b))
print(b.shape)



In [ ]:
# Exercise 10 - transpose the array b.
print(b)
print(np.transpose(b))


In [ ]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. 
#(1 x 6)
print(np.transpose(b).reshape(1,6))



In [ ]:
# Exercise 12 - reshape the array b to be a list of 6 lists, 
#each containing only 1 number (6 x 1)
print(np.reshape(6,1))




In [ ]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c.
print(np.min(c))



In [ ]:
# Exercise 2 - Determine the standard deviation of c.
print(np.std(c))


In [ ]:
# Exercise 3 - Determine the variance of c.
print(np.var(c))


In [ ]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)


In [ ]:
# Exercise 5 - Transpose c and print out transposed result.
print(c)
print(np,transpose(c))


In [ ]:
# Exercise 6 - Get the dot product of the array c with c. 
print(np.dot(c, c))


In [ ]:
# Exercise 7 - Write the code necessary to sum up the result of c 
#times c transposed. Answer should be 261
print(np.sum(np.multiply(c,(np.tranpose(c)))))

In [ ]:
# Exercise 8 - Write the code necessary to determine the 
#product of c times c transposed. Answer should be 131681894400.
print(np.product(np.multiply(c,(np.transpose(c)))))

In [ ]:
## Setup 4
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

# Exercise 1 - Find the sine of all the numbers in d




In [ ]:

# Exercise 2 - Find the cosine of all the numbers in d



In [ ]:
# Exercise 3 - Find the tangent of all the numbers in d



In [ ]:
# Exercise 4 - Find all the negative numbers in d




In [ ]:
# Exercise 5 - Find all the positive numbers in d




In [ ]:
# Exercise 6 - Return an array of only the unique numbers in d.




In [ ]:
# Exercise 7 - Determine how many unique numbers there are in d.




In [ ]:
# Exercise 8 - Print out the shape of d.




In [ ]:
# Exercise 9 - Transpose and then print out the shape of d.




In [122]:
# Exercise 10 - Reshape d into an array of 9 x 2

