In [14]:
%matplotlib inline
import numpy as np
import pandas as pd

np.random.seed(29)

Rolling two dice. what is the probability of rolling 2 even numberes?

In [10]:
def probability_of_even():
    two_dice = 36
    even_two_dice = 9
    prob = even_two_dice/two_dice
    return prob
print(probability_of_even())


0.25


Calculate this probability exactly and using simulation

#Adam's way

In [54]:
rng = np.random.default_rng(seed = 42)


In [50]:
my_array = rng.integers(1,7, (10_000, 2))
my_array[:5]

array([[4, 6],
       [5, 5],
       [5, 1],
       [2, 5],
       [3, 6]])

In [51]:
my_array % 2 == 0

array([[ True,  True],
       [False, False],
       [False, False],
       ...,
       [ True,  True],
       [ True, False],
       [False,  True]])

In [52]:
num_evens = (my_array % 2 == 0).sum(axis = 1)
num_evens[:5]

array([2, 0, 0, 1, 1])

In [53]:
(num_evens == 2).mean()

0.2476